### ISSUE TITLE
TypeError: Cannot read property 'contextio' of undefined

### ISSUE THREAD

**Issue by zeroasterisk** [rapito/meteor-contextio#3]
Brand new Meteor app, first package, getting the following error output on server console:

```
(STDERR) /Users/admin/.meteor/packages/meteor-tool/.1.1.3.ufzkvm++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
(STDERR) 						throw(ex);
(STDERR) 						      ^
(STDERR) TypeError: Cannot read property 'contextio' of undefined
(STDERR)     at Function.ContextIOClient.ContextIOClient.get (packages/rapito:contextio/server/lib/ContextIOClient.coffee:96:36)
(STDERR)     at __coffeescriptShare (packages/rapito:contextio/server/lib/ContextIOClient.coffee:103:23)
(STDERR)     at packages/rapito:contextio/server/lib/ContextIOClient.coffee:1:1
(STDERR)     at packages/rapito:contextio/both/lib/methods/ContextIOClient.coffee:1:1
(STDERR)     at /Development/xxxx/app/.meteor/local/build/programs/server/boot.js:222:10
(STDERR)     at Array.forEach (native)

```

**Comment by rapito** [comment]
@zeroasterisk  Are you using it on Client side? If you are, then that's why you get the error. It's only available on Server side.

**Comment by sbr464** [comment]
I'm also having this issue

 TypeError: Cannot read property 'contextio' of undefined
W20150803-02:38:14.828(-6)? (STDERR)     at Function.ContextIOClient.ContextIOClient.get (packages/rapito:contextio/server/lib/ContextIOClient.coffee:96:36)
W20150803-02:38:14.828(-6)? (STDERR)     at __coffeescriptShare (packages/rapito:contextio/server/lib/ContextIOClient.coffee:103:23)
W20150803-02:38:14.829(-6)? (STDERR)     at packages/rapito:contextio/server/lib/ContextIOClient.coffee:1:1

**Comment by rapito** [comment]
@sbr464 Can you show the line of code which you are calling to get this error?

**Comment by sbr464** [comment]
Hi, it turned out the issue was not defining the contextio info in the meteor.settings file. 

I was trying to ignore that method and create the key/variable directly, but that error was preventing. I added the meteor.settings info for context and it worked.

**Comment by zeroasterisk** [comment]
I am also not using it in the meteor.settings file - I'll switch to that and see if it resolves things.

**Comment by rapito** [comment]
It IS required, I will update the README.md to make sure everyone includes it. Thanks!
