### ISSUE TITLE
TypeError: Object [object Object] has no method 'get'

### ISSUE THREAD

**Issue by yangez** [rapito/meteor-contextio#4]
When trying `var cio = Cio.get()` I get `TypeError: Object [object Object] has no method 'get'`. I've set up the settings.json file correctly, and I'm calling it from the server. What am I doing wrong?

**Comment by rapito** [comment]
Thanks @yangez, The readme is misleading, will fix asap.

```Cio``` is a singleton ready for use out of the box: 
> i.e: 
```
Cio.createAccount(user.mail, user.name, user.lastname)
```

**Comment by yangez** [comment]
Got it. Thanks
